### ISSUE TITLE
Unreadable Logs on K8s v1.6

### ISSUE THREAD

**Issue by salilgupta1** [SumoLogic/fluentd-kubernetes-sumologic#20]
I'm seeing the same issue as #11 

```
/mnt/log/containers/kube-apiserver-ip-10-131-51-160.ec2.internal_kube-system_kube-apiserver-c7a8163d649d8c56993670717b8aaa72704a7a9930aa115bd45971072f0ac96d.log unreadable. It is excluded and would be examined next time
```
I deployed the DaemonSet and Secret on my K8s cluster following the directions of the README file and it worked on my v1.5 cluster, but when I deployed it to my v1.6 cluster I got the above issue. 

Differences between my v1.5 and v1.6 cluster set up:
- v1.6 is using RBAC roles to restrict resources to within their namespace
- Consequently, the kube-system has permissions across all namespaces and therefore I deployed the DameonSet and Secret to that namespace.  (Was getting a permissions issue when I deployed to the default namespace)

Has anyone seen this issue on v1.6?

**Comment by frankreno** [comment]
@salilgupta1 : are you using the default configuration for the daemonet or have you customized it at all?

**Comment by salilgupta1** [comment]
@frankreno we're using Kops to bring up the cluster. The DaemonSet is the standard configuration - only thing I added was ```namespace: kube-system``` to the metadata.

**Comment by i02sopop** [comment]
I have also this issue in kubernetes 1.6.1. Is there any known fix?

**Comment by salilgupta1** [comment]
I haven't tried it out yet, but this seems relevant: 
https://github.com/fabric8io/docker-fluentd-kubernetes/issues/14

**Comment by i02sopop** [comment]
Everything indicates it's some bad links. In the directory `/mnt/log/containers` there's one link per pod, but it's linked against `/var/log/pods` directory instead of `/mnt/log/pods` directory.

**Comment by i02sopop** [comment]
I solved it for my environment. What I've done is change the daemonSet of sumologic to mount the log volume on /var/log instead of on /mnt/log and create a docker image based on `sumologic/fluentd-kubernetes-sumologic:latest` with new versions of `source.kubernetes.conf` and `source.containers.conf` that replaces `/mnt/log` by `/var/log` in order to scrape correctly the logs.

**Comment by frankreno** [comment]
@i02sopop : thank you for figuring this out.  It looks like the mount paths changed between k8s 1.5 and 1.6.  I will look at the best way to solve this and get the appropriate changes made as well as get proper versions in DockerHub.

**Comment by frankreno** [comment]
I am thinking what we will do is create an environment variable for the mount path so that it can overridden.  Pre 1.6, the current path works fine (testing on 1.4 and 1.5).  However 1.6 has changed the paths so we need to update the mount path accordingly.  Plan is to get this done this week and get the new image pushed to Docker hub so you do not have to also maintain the image.

**Comment by frankreno** [comment]
Actually, you can do this without modifying the config files OR creating your image.  You can correct this by updating only the `fluentd.daemonset.yaml` container volume mounts.  If you change
